datasource:
  url: jdbc:mysql://localhost:3306/libreria?useSSL=false&serverTimezone=UTC
  username: ${db_username}
  password: ${db_password}
jpa:
  hibernate:
    ddl-auto: none
  show-sql: true
  properties:
    hibernate:
      format_sql: true
server:
  port: 8080